### ISSUE TITLE
どうしてこうなった

### ISSUE THREAD

**Issue by unoemon** [FUJITOSHION/TrafficLight#18]
![2018-10-30 14 54 49](https://user-images.githubusercontent.com/17404403/47698725-c4fb4d00-dc53-11e8-9e25-fb5895b30e18.png)

![dousite](https://user-images.githubusercontent.com/17404403/47698704-b57c0400-dc53-11e8-841a-9712b284ba7d.jpeg)

**Comment by FUJITOSHION** [comment]
インデントについて自分が誤解してました何度もissueしてもらいすいません
